name: build

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Test pip installation
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest --cov dna_mutator
